---

- name: ansible filter examples
  hosts: localhost
  vars:
    martin:
      name: Martin D'veloper
      job: Developer
      skills:
        - ansible
        - python
        - perl
        - ruby
      url: https://github.com/frankhjung/ansible-filters

  tasks:

    - block:

      - name: show data structure
        debug:
          var: martin

      tags: always

    # create
    - block:

      - name: list skills
        debug:
          var: item
        with_items: "{{ martin.skills }}"

      - name: count skills
        set_fact:
          skills_length: "{{ martin.skills | length }}"

      - name: show skills count
        debug:
          msg: "martin has {{ skills_length }} skills"

      tags: create

    # subset
    - block:

      - name: list skills
        debug:
          var: item
        with_items: "{{ martin.skills }}"

      - name: show skill starting with 'p'
        debug:
          var: item
        with_items: "{{ martin.skills }}"
        when: item | match('p.*')

      - name: show skills except 'perl'
        debug:
          var: item
        with_items: "{{ martin.skills }}"
        when: not item | match('perl') # same as item != 'perl'

      tags: subset

    # manipulate
    - block:

      - name: show name
        debug:
          var: martin.name

      - name: split name into a list
        debug:
          var: item
        with_items: "{{ martin.name.split(' ') }}"

      - name: show job
        debug:
          var: martin.job

      - name: change job to lowercase
        debug:
          msg: "{{ martin.job | lower }}"

      - name: list skills
        debug:
          var: item
        with_items: "{{ martin.skills }}"

      - name: sort skills
        debug:
          var: item
        with_items: "{{ martin.skills | sort(reverse=True) }}"

      - name: capitalize skills
        debug:
          msg: "{{ item | capitalize }}"
        with_items: "{{ martin.skills }}"

      tags: manipulate

    # regex
    - block:

        - name: search using regex named group
          debug:
            msg: "{{ martin.url | regex_replace('.*/(?P<war>.+)$', '\\g<war>') }}"

        - name: search using regex numbered group
          debug:
            msg: "{{ martin.url | regex_replace('.*/(.+)$', '\\1') }}"

      tags: regex

    # other
    - block:

      - name: write data structure to yaml
        copy:
          content: "{{ martin | to_nice_yaml(indent=4) }}"
          dest: './martin.yaml'

      tags: other

    # test filter plugin
    - block:

      - name: count number of occurrences of 'r' in name
        set_fact:
          counter: "{{ martin.name | count('r') }}"

      - name: test there are exactly 2 occurrences
        debug:
          var: counter
        failed_when: counter | int != 2

      tags: test
